name: Build iOS
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      MODE: release
      TARGET_OS: ios
      TARGET_ARCH: ${{ matrix.arch }}
      BRANDING: ${{ matrix.branding }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        arch: [arm64,x64]
        branding: [neuromore]
    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_GITHUB_ACTIONS }}
        lfs: false

    # Load Dependencies from Cache
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: |
          deps/build/make/bin/osx-x64
          deps/build/make/bin/ios-*
          deps/build/make/lib/ios-*
        key: dependencies-${{ env.BRANCH_NAME }}-${{ env.TARGET_OS }}-${{ env.TARGET_ARCH }}-${{ matrix.os }}-${{ hashFiles('deps/VERSION') }}

    # Build QtTools (OSX-X64)
    - name: Build QtTools (OSX-X64)
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: make TARGET_OS=osx TARGET_ARCH=x64 QtTools -j${{ env.JOBS }}

    # Build Dependencies
    - name: Build Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: make Dependencies -j${{ env.JOBS }}

    # Build Engine
    - name: Build Engine
      run: make Engine -j${{ env.JOBS }}

    # Build EngineLIB
    - name: Build EngineLIB
      run: make EngineLIB -j${{ env.JOBS }}

    # Build QtBase
    - name: Build QtBase
      run: make QtBase -j${{ env.JOBS }}

    # Upload Engine
    - name: Upload Engine
      uses: actions/upload-artifact@v3
      with:
        name: Engine-${{ matrix.arch }}-${{ matrix.branding }} (${{ matrix.os }})
        path: |
          ./src/Engine/neuromoreEngine.h
          ./build/make/lib/ios-${{ matrix.arch }}/EngineLIB.dylib
