name: Debug CI Windows
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
    steps:

    # Test
    - name: Test
      shell: cmd
      run: timeout /T $(1) /NOBREAK >nul 2>&1
