name: Debug CI Windows
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
    steps:

    # Test
    - name: Test
      run: |
        "C:\Program Files\Windows Defender\MpCmdRun.exe" -Scan -ScanType 3 -File ./Makefile

    - name: Test2
      run: Set-MpPreference -DisableRealtimeMonitoring $true