name: Debug CI Windows
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
    steps:

    # Manual Defender Scan
    - name: Manual Defender Scan
      run: |
        Start-MpScan -ScanType CustomScan -ScanPath ${{ github.workspace }}
        Set-MpPreference -ExclusionPath ${{ github.workspace }}
        Set-MpPreference -DisableRealtimeMonitoring $true
        Get-MpComputerStatus

