name: Debug CI Windows
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_GITHUB_ACTIONS }}
        lfs: false

    - name: Test cmd
      shell: cmd
      run: |
        make -f test.mk

    - name: Test pwsh
      shell: pwsh
      run: |
        make -f test.mk
